var arrLang                    = new Array();
arrLang['en']                  = new Array();
arrLang['in']                  = new Array();


arrLang['en']['sectionplanone1']   = 'The #1 Virtual Office in Indonesia';
arrLang['en']['sectionplanone2']   = 'vOffice offers you the best virtual office solutions minus the tricky addons and hidden costs. By utilizing the latest technology, your business can capitalize on the latest technology to give you a commercial advantage.';
arrLang['en']['sectionplantwo1']   = 'Businesses can now have a prestigious business presence in Jakarta for as little as Rp 600.000 a month. Our trained receptionist will take your calls, managed and notify you of your mails, attend to your guest and more. You can also meet in one of our 30+ meeting rooms in Jakarta, Surabaya and Bali.';
arrLang['en']['sectionplantwo2']   = 'Qualified plans even comes with a domicile certification for company incorporation purposes.';
arrLang['en']['sectionplantwo3']   = 'vOffice offers you the best virtual office solutions minus the tricky addons and hidden costs. Pick your virtual office plans now and start growing your business.';
arrLang['en']['sectionplanthree1'] = 'PLAN DETAILS';
arrLang['en']['sectionplanfour1']  = 'BUSINESS ADDRESS';
arrLang['en']['sectionplanfour2']  = 'Prestigious Business Address';
arrLang['en']['sectionplanfour3']  = 'Receive Mails & Parcels';
arrLang['en']['sectionplanfour4']  = 'SMS or Email Notification Sent to you within 4 hours';
arrLang['en']['sectionplanfour5']  = 'Elegant Reception Service';
arrLang['en']['sectionplanfive1']  = 'CALL HANDLING';
arrLang['en']['sectionplanfive2']  = 'Dedicated Local Telephone Number';
arrLang['en']['sectionplanfive3']  = 'Professional Call Answering';
arrLang['en']['sectionplanfive4']  = 'SMS or Email Notification';
arrLang['en']['sectionplanfive5']  = 'Free Call Transfer Worldwide';
arrLang['en']['sectionplanfive6']  = 'Personalized Voicemail';
arrLang['en']['sectionplansix1']   = 'FAX SERVICE';
arrLang['en']['sectionplansix2']   = 'Dedicated Local Fax Number';
arrLang['en']['sectionplansix3']   = 'Instant Fax Forwarding to your Email';
arrLang['en']['sectionplanseven2'] = 'Meeting Room';
arrLang['en']['sectionplaneight1'] = 'OTHER BENEFITS';
arrLang['en']['sectionplaneight2'] = 'Lowest Possible Rate';
arrLang['en']['sectionplaneight3'] = '*Free Domisili Kelurahan and Gedung';
arrLang['en']['sectionplaneight4'] = 'vOffice Elite Card';
arrLang['en']['sectionplaneight5'] = '*For 12 months virtual office package';
arrLang['en']['sectionplanten1']   = 'PRICING';
arrLang['en']['sectionplanten2']   = 'Pick your Virtual Office plan now at your preferred location and gain the edge over your competitor.';
arrLang['en']['sectionplannine1']  = 'BENEFITS';
arrLang['en']['sectionplannine2']  = 'LOCATION';
arrLang['en']['sectionplannine4']  = 'Split Payment Options now available!';
arrLang['en']['sectionplannine5']  = 'You can now pay for your 24 or 36 months plan in 3 equal payments within 3 months. Call us at +6221 2922 2999 to find out more!';
arrLang['en']['sectionplannine6']  = 'Professional Receptionist';
arrLang['en']['sectionplannine7']  = 'High Speed Internet';
arrLang['en']['sectionplannine8']  = 'vButtler';
arrLang['en']['sectionplannine9']  = 'Events, Community & Workshops';
arrLang['en']['sectionplannine10'] = 'Phone Number/Call Answering Service';
arrLang['en']['sectionplannine11'] = 'Speciality Coffee';
arrLang['en']['sectionplannine12'] = 'Audio & Visual Equipment';
arrLang['en']['sectionplannine13'] = 'Access to Cre8 Coworking Space';
arrLang['en']['sectionplannine14'] = 'Privileges Card';
arrLang['en']['sectionplannine15'] = 'Pasport to Cre8 & vOffice Conference';
arrLang['en']['sectionplannine16'] = 'Free 15 Hours Meeting Rooms';
arrLang['en']['sectionplannine17'] = 'Free Access to "Entreprenity" Our Global Online Platform';
arrLang['en']['sectionplannine18'] = 'All prices in Indonesia Rupiah (IDR). Prices shown exclude 6% GST and is after pre-payment discount. Promo price valid for new sign up only.';
arrLang['in']['sectionplanone1']   = 'Virtual Office Terbaik di Indonesia';
arrLang['in']['sectionplanone2']   = 'vOffice menawarkan Anda solusi virtual terbaik dengan biaya transparan dan tanpa proses yang rumit. Dengan memanfaatkan teknologi terbaru, bisnis Anda akan mendapatkan keuntungan komersil yang signifikan.';
arrLang['in']['sectionplantwo1']   = 'Kini perusahaan bisa memiliki alamat bisnis bergengsi di Jakarta hanya dengan Rp 600.000 setiap bulannya. Resepsionis kami yang terlatih akan menerima telepon Anda, memilahnya dan memberi tahu Anda jika ada surat datang, menyambut tamu Anda dan banyak lagi. Anda juga dapat mengadakan rapat di salah satu ruang meeting kami di lebih dari 30 lokasi di Jakata, Surabaya dan Bali.';
arrLang['in']['sectionplantwo2']   = 'Paket kami yang berkualitas disertai dengan surat domisili untuk keperluan pembuatan PT Anda.';
arrLang['in']['sectionplantwo3']   = 'vOffice menawarkan Anda solusi virtual terbaik dengan biaya transparan dan tanpa proses yang rumit. Pilih paket virtual office Anda dan mulai mengembangkan bisnis Anda.';
arrLang['in']['sectionplanthree1'] = 'RINCIAN PAKET';
arrLang['in']['sectionplanfour1']  = 'ALAMAT BISNIS';
arrLang['in']['sectionplanfour2']  = 'Alamat Bisnis Bergengsi';
arrLang['in']['sectionplanfour3']  = 'Penerimaan Surat & Paket';
arrLang['in']['sectionplanfour4']  = 'Notifikasi melalui SMS atau Email Dikirimkan pada Anda dalam 4 jam';
arrLang['in']['sectionplanfour5']  = 'Layanan Resepsionis yang Berkelas';
arrLang['in']['sectionplanfive1']  = 'PENANGANAN TELEPON';
arrLang['in']['sectionplanfive2']  = 'Nomor Telepon Lokal Khusus';
arrLang['in']['sectionplanfive3']  = 'Layanan Penjawab Telepon Profesional';
arrLang['in']['sectionplanfive4']  = 'Notifikasi melalui SMS atau Email';
arrLang['in']['sectionplanfive5']  = 'Gratis Transfer Panggilan ke Seluruh Dunia';
arrLang['in']['sectionplanfive6']  = 'Pesan Suara Khusus';
arrLang['in']['sectionplansix1']   = 'LAYANAN FAKS';
arrLang['in']['sectionplansix2']   = 'Nomor Faks Lokal Khusus';
arrLang['in']['sectionplansix3']   = 'Penerusan Faks Instan ke Email Anda';
arrLang['in']['sectionplanseven2'] = 'Ruang Meeting';
arrLang['in']['sectionplaneight1'] = 'KEUNTUNGAN LAIN';
arrLang['in']['sectionplaneight2'] = 'Harga Paling Rendah';
arrLang['in']['sectionplaneight3'] = '*Gratis Domisili Kelurahan dan Domisili Gedung';
arrLang['in']['sectionplaneight4'] = 'vOffice Elite Card';
arrLang['in']['sectionplaneight5'] = '*Untuk paket virtual office selama 12 bulan';
arrLang['in']['sectionplanten1']   = 'DAFTAR HARGA';
arrLang['in']['sectionplanten2']   = 'Pilih paket virtual office Anda dan jadi selangkah lebih cepat dari kempetitor Anda.';
arrLang['in']['sectionplannine1']  = 'KEUNTUNGAN';
arrLang['in']['sectionplannine2']  = 'LOKASI';
arrLang['in']['sectionplannine4']  = 'Sekarang Anda Bisa Mengangsur Pembayaran!';
arrLang['in']['sectionplannine5']  = 'Anda bisa membayar paket 24 bulan atau 36 bulan sebanyak 3 kali selama 3 bulan. Hubungi kami di +6221 2922 2999 untuk informasi lebih lanjut! ';
arrLang['in']['sectionplannine6']  = 'Resepsionis Profesional';
arrLang['in']['sectionplannine7']  = 'Internet Cepat';
arrLang['in']['sectionplannine8']  = 'vButtler';
arrLang['in']['sectionplannine9']  = 'Acara, Komunita & Workshop';
arrLang['in']['sectionplannine10'] = 'Nomor Telepon / Layanan Penjawab Telepon';
arrLang['in']['sectionplannine11'] = 'Kopi Berkualitas';
arrLang['in']['sectionplannine12'] = 'Peralatan Audio & Visual';
arrLang['in']['sectionplannine13'] = 'Akses ke Cre8 Coworking Space';
arrLang['in']['sectionplannine14'] = 'Privilege Card';
arrLang['in']['sectionplannine15'] = 'Akses ke Konferensi Cre8 & vOffice';
arrLang['in']['sectionplannine16'] = 'Gratis 15 Jam Penggunaan Ruang Meeting';
arrLang['in']['sectionplannine17'] = 'Akses ke "Entreprenity", Platform Online Kami yang Mendunia';
arrLang['in']['sectionplannine18'] = 'Seluruh harga Dalam Rupish (IDR). Harga yang tercantum belum termasuk PPN 10%.  Harga promo hanya berlaku untuk pendaftaran baru saja.';
arrLang['en']['footerone1']   = 'View All vOffice Locations';
arrLang['in']['footerone1']   = 'Lihat Seluruh Lokasi vOffice';
arrLang['en']['footerone2']   = 'Company Incorporation';
arrLang['in']['footerone2']   = 'Pembuatan PT, CV, & PMA';
arrLang['en']['footerone3']   = 'Sign up for more Virtual Office Indonesia offers';
arrLang['in']['footerone3']   = 'Daftar untuk Melihat lebih banyak Penawaran Virtual Office Indonesia';
arrLang['en']['footerone4']   = 'Since 2003. Virtual Office Indonesia (vOffice) has served over 22,000 businesses and available in over 42 locations. Virtual Office Indonesia enable businesses to scale fast and operate leanly. For more information about virtual office Indonesia, please call us at +603 2788 3555 or email us at cs@voffice.com.my';
arrLang['in']['footerone4']   = 'Sejak 2003, Virtual Office Indonesia (vOffice) telah melayani lebih dari 22.000 bisnis dan tersedia di lebih dari 42 lokasi. Virtual Office Indonesia memudahkan bisnis untuk berkembang pesat dan beroperasi dengan mudah. Untuk informasi lebih lanjut mengenai Virtual Office Indonesia, silakan hubungi kami di +6221 2922 2999 atau kirimkan email ke cs@voffice.co.id';

$(document).ready(function(e) {
        $('.translate').click(function(){
            var lang = $(this).attr('id');

            $('.lang').each(function(endex, element){
                $(this).text(arrLang[lang][$(this).attr('key')]);
            });
    });
});

